include ../default.mk

$(EXE_DIR)/tests/Trie_tests: $(OBJ_DIR)/tests/catch_main.o
$(EXE_DIR)/tests/heapsort_tests: $(OBJ_DIR)/tests/catch_main.o
$(EXE_DIR)/tests/mergesort_tests: $(OBJ_DIR)/tests/catch_main.o
$(EXE_DIR)/tests/memory_allocator_tests: $(OBJ_DIR)/tests/catch_main.o