include ../default.mk

$(EXE_DIR)/range_sum_query_2D_immutable: $(OBJ_DIR)/range_sum_query_2D_immutable-main.o $(OBJ_DIR)/range_sum_query_2D_immutable_c.o
$(EXE_DIR)/range_sum_query_2D_immutable-main: $(OBJ_DIR)/range_sum_query_2D_immutable.o $(OBJ_DIR)/range_sum_query_2D_immutable_c.o
$(EXE_DIR)/range_sum_query_2D_immutable_c: $(OBJ_DIR)/range_sum_query_2D_immutable.o $(OBJ_DIR)/range_sum_query_2D_immutable-main.o
