CXXFLAGS += -O3
IGNORE_EXES += $(EXE_DIR)/range_sum_query_2D_immutable $(EXE_DIR)/range_sum_query_2D_immutable_c

include ../default_Makefile

$(EXE_DIR)/range_sum_query_2D_immutable-main: $(OBJ_DIR)/range_sum_query_2D_immutable_c.o
