# LDFLAGS += -larmadillo $(shell pkg-config --libs plplot-c++) -lpthread
CXXFLAGS += -O3
IGNORE_EXES += $(EXE_DIR)/range_sum_query_2D_immutable

include ../default_Makefile

$(EXE_DIR)/range_sum_query_2D_immutable-main: $(OBJ_DIR)/range_sum_query_2D_immutable.o
